instrument:
  class_name: DigitalTwin
  file: asyncroscopy/instruments/electron_microscope/digital_twin.py
  description: "Test Digital Twin"
  timeout_seconds: 120

devices:
  camera:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.camera
  data:
    module_name: asyncroscopy.data.data
  eds:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.eds
  flucam:
    module_name: asyncroscopy.instruments.electron_microscope.detectors.flucam
  scan:
    module_name: asyncroscopy.instruments.electron_microscope.hardware.scan
  stage:
    class_name: TestStage
    module_name: asyncroscopy.instruments.electron_microscope.hardware.TestStage

tango:
  host: localhost
  port: 9094
  reset_database_file: false

tiled:
  host: localhost
  port: 9091
  acquisition_dir: outputs/tiled_acquisitions
  autostart: true
  register_on_startup: false

device_timeout_seconds: 120
